### ISSUE TITLE
Upgrade bx-slider

### ISSUE THREAD

**Issue by betesh** [manfe/bxslider-rails#10]
I'm having problems precompiling because https://github.com/stevenwanderski/bxslider-4/issues/48 hasn't been merged into bxslider-rails yet.

**Comment by betesh** [comment]
Specifically, precompile fails because of this line: https://github.com/manfe/bxslider-rails/blob/v4.2.5/vendor/assets/javascripts/jquery.bxslider.js#L237

**Comment by manfe** [comment]
@betesh If you check the lastest version on https://github.com/stevenwanderski/bxslider-4 and check the file https://github.com/stevenwanderski/bxslider-4/blob/master/dist/jquery.bxslider.js#L237.

You will see that the float attribute is not between quotes, my guess is that they merged but later removed it again.

I will open an pull request on their repo, but first I will change it directly here and update the gem.

I will let you know when it's fixed.

**Comment by manfe** [comment]
@betesh the gem was updated and tested with the YUI compressor and it's working fine now. Use in your gem file:  `gem 'bxslider-rails', '~> 4.2.5.1'`

Also, I created a pull request to fix on bxslider-4 repo, you can follow here: https://github.com/stevenwanderski/bxslider-4/issues/48

**Comment by betesh** [comment]
Thanks for the quick response!  Precompile works again!
