### ISSUE TITLE
Rails 4.2.0 - Assets not working for production

### ISSUE THREAD

**Issue by tayyabshabab** [manfe/bxslider-rails#9]
I am implementing bxslider-rails for rails rails 4.2.0. It works fine on localhost but on production server the assets are not showing up.

I have added this line in my assets.rb file
config.assets.precompile += %w( bx_loader.gif controls.png )

But still the files controls.png and bx_loader.gif are missing.

**Comment by systemnate** [comment]
I'm having the same problem.

**Comment by ctmaloney** [comment]
+1

**Comment by manfe** [comment]
Guys, I have to say sorry for you. I made the merge to fix it, but forgot to release the gem to rubygems servers.

Now it's ok.
